#!/usr/bin/env python3

import csv

class reader(obj):
   '''
      A simple class used to perform read operations
      on a csv file.
   '''

   def read(self, csv_file):
      '''
         simply read a csv file and return its contents
      '''

      with open(csv_file, 'r') as f:
        cs = csv.reader(f)

        cs = [row for row in cs]

      df = dict()
      for key in cs[0]:
         df[key] = []

      df_keys = [key for key in df.keys()]
      for row in cs[1: ]:
         for i, col in enumerate(row):
            df[df_keys[i]].append(col)

      return df
